### ISSUE TITLE
Add StringConcatenator

### ISSUE THREAD

**Issue by frankbuckley** [dseinternational/open-dotnet#79]
Something like the following - in DSE.Open assembly, DSE.Open.Text namespace.

- [ ] and tests

Main use is to concat list of values with commas and a final "and" or "or".

We could also consider:

- Not using StringBuilder, but rather calculating required length upfront and allocation char[]
- Handing off to `(ReadOnlySpan<char> separator, ReadOnlySpan<string?> values)` overload? (See [here](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs,913))
- `(char separator, IEnumerable<string> values, char? finalSeparator = null)` overload
- Should this be part of `StringHelper`?

```c#
public static class StringConcatenator
{
    public static string Join(string separator, IEnumerable<string> values, string? finalSeparator = null)
    {
        ArgumentNullException.ThrowIfNull(separator);
        ArgumentNullException.ThrowIfNull(values);

        if (finalSeparator is null)
        {
            return string.Join(separator, values);
        }

        var sb = new StringBuilder();

        if (values is ICollection<string> collection)
        {
            var count = collection.Count;

            if (count == 0)
            {
                return string.Empty;
            }

            var i = 0;

            foreach (var s in collection)
            {
                _ = sb.Append(s);

                if (i < count - 2)
                {
                    _ = sb.Append(separator);
                }
                else if (i == count - 2)
                {
                    _ = sb.Append(finalSeparator);
                }

                i++;
            }

            return sb.ToString();
        }

        using (var en = values.GetEnumerator())
        {
            if (!en.MoveNext())
            {
                return string.Empty;
            }

            var firstValue = en.Current;

            if (!en.MoveNext())
            {
                // Only one value available
                return firstValue ?? string.Empty;
            }

            _ = sb.Append(firstValue);

            var isLast = false;

            while (!isLast)
            {
                var current = en.Current;

                isLast = !en.MoveNext();

                if (isLast)
                {
                    _ = sb.Append(finalSeparator);
                }
                else
                {
                    _ = sb.Append(separator);
                }

                _ = sb.Append(current);
            }
        }

        return sb.ToString();
    }

```

**Comment by frankbuckley** [comment]
I have fleshed out some more overloads and gone with adding to StringHelper in #84 

Still to do:

- [ ] extend test coverage (repurpose StringConcatenatorTests?)
- [ ] consider (and benchmark) optimisations
- [ ] what (if anything) can we do for our value types that are ISpanFormattable and could implement ISpanFormatableCharCountProvider

**Comment by frankbuckley** [comment]
| Method                 | ValuesCount | Values               | Mean        | Error    | StdDev   | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|----------------------- |------------ |--------------------- |------------:|---------:|---------:|------:|--------:|-------:|----------:|------------:|
| StringConcatenatorJoin | 5           | IEnumerable<string>  |   210.41 ns | 0.838 ns | 0.743 ns |  1.49 |    0.01 | 0.0007 |     586 B |        1.01 |
| StringHelperJoin       | 5           | IEnumerable<string>  |   140.83 ns | 0.649 ns | 0.575 ns |  1.00 |    0.00 | 0.0007 |     578 B |        1.00 |
|                        |             |                      |             |          |          |       |         |        |           |             |
| StringConcatenatorJoin | 5           | List<string>         |    61.89 ns | 0.286 ns | 0.253 ns |  1.68 |    0.01 | 0.0002 |     184 B |        1.35 |
| StringHelperJoin       | 5           | List<string>         |    36.88 ns | 0.174 ns | 0.145 ns |  1.00 |    0.00 | 0.0002 |     136 B |        1.00 |
|                        |             |                      |             |          |          |       |         |        |           |             |
| StringConcatenatorJoin | 5           | Collection<string>   |   150.04 ns | 0.467 ns | 0.414 ns |  1.53 |    0.01 | 0.0002 |     200 B |        0.93 |
| StringHelperJoin       | 5           | Collection<string>   |    98.06 ns | 0.511 ns | 0.478 ns |  1.00 |    0.00 | 0.0002 |     216 B |        1.00 |
|                        |             |                      |             |          |          |       |         |        |           |             |
| StringConcatenatorJoin | 20          | IEnumerable<string>  |   571.00 ns | 3.373 ns | 3.155 ns |  1.31 |    0.01 | 0.0019 |    1554 B |        1.09 |
| StringHelperJoin       | 20          | IEnumerable<string>  |   437.33 ns | 1.527 ns | 1.428 ns |  1.00 |    0.00 | 0.0019 |    1432 B |        1.00 |
|                        |             |                      |             |          |          |       |         |        |           |             |
| StringConcatenatorJoin | 20          | List<string>         |   262.43 ns | 1.126 ns | 1.053 ns |  2.74 |    0.02 | 0.0010 |     752 B |        2.19 |
| StringHelperJoin       | 20          | List<string>         |    95.75 ns | 0.522 ns | 0.436 ns |  1.00 |    0.00 | 0.0004 |     344 B |        1.00 |
|                        |             |                      |             |          |          |       |         |        |           |             |
| StringConcatenatorJoin | 20          | Collection<string>   |   266.33 ns | 1.331 ns | 1.180 ns |  1.09 |    0.01 | 0.0010 |     752 B |        1.54 |
| StringHelperJoin       | 20          | Collection<string>   |   243.42 ns | 1.614 ns | 1.510 ns |  1.00 |    0.00 | 0.0005 |     488 B |        1.00 |
|                        |             |                      |             |          |          |       |         |        |           |             |
| StringConcatenatorJoin | 100         | IEnumerable<string>  | 2,208.38 ns | 8.249 ns | 6.440 ns |  1.33 |    0.01 | 0.0038 |    5192 B |        1.06 |
| StringHelperJoin       | 100         | IEnumerable<string>  | 1,655.84 ns | 9.951 ns | 8.821 ns |  1.00 |    0.00 | 0.0057 |    4896 B |        1.00 |
|                        |             |                      |             |          |          |       |         |        |           |             |
| StringConcatenatorJoin | 100         | List<string>         |   777.43 ns | 3.537 ns | 3.308 ns |  1.97 |    0.01 | 0.0038 |    2928 B |        1.95 |
| StringHelperJoin       | 100         | List<string>         |   394.59 ns | 1.557 ns | 1.457 ns |  1.00 |    0.00 | 0.0019 |    1504 B |        1.00 |
|                        |             |                      |             |          |          |       |         |        |           |             |
| StringConcatenatorJoin | 100         | Collection<string>   |   779.73 ns | 3.797 ns | 3.552 ns |  0.74 |    0.00 | 0.0038 |    2928 B |        1.79 |
| StringHelperJoin       | 100         | Collection<string>   | 1,047.95 ns | 4.094 ns | 3.830 ns |  1.00 |    0.00 | 0.0019 |    1632 B |        1.00 |

**Comment by rabuckley** [comment]
This is all there and we have some benchmarks. We could probably improve perf and de-duplicate some code, but we'd be hitting diminishing returns. Think we can call this done for now.
