### ISSUE TITLE
Reorder parameters for StringHelper.Join

### ISSUE THREAD

**Issue by frankbuckley** [dseinternational/open-dotnet#88]
We should change these (before it breaks too much) to:

```c#
    public static string Join(string? separator, string? finalSeparator, IEnumerable<string?> values)
```

We can then [later make it](https://github.com/dotnet/csharplang/blob/main/proposals/params-collections.md):

```c#
    public static string Join(string? separator, string? finalSeparator, params IEnumerable<string?> values)
```

**Comment by rabuckley** [comment]
Is it really a common use case that they're not already in a collection. It's also not hard to add the collection expression syntax around the params inline.

Basically, what I'm saying is I don't see the need for `params` given how easy it is to make collections.
